stages:
  - tests
  - deploy-docs

cache:
  key:
    files:
      - pyproject.toml
  paths:
    - .cache/uv

variables:
  UV_CACHE_DIR: ".cache/uv"

.env_setup: &env_setup
  before_script:
    # Install system dependencies
    - apt-get update && apt-get install -y --no-install-recommends libgdal-dev g++ libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 rsync openssh-client
    
    # Configure GDAL environment
    - export GDAL_VERSION=$(gdal-config --version)
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
    
    # Sync dependencies
    - uv add "gdal==${GDAL_VERSION}.*"
    - uv sync --all-extras --dev

test-module:
  stage: tests
  tags:
    - docker
  image:
    name: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    pull_policy: [if-not-present, always]
  <<: *env_setup
  script:
    - uv run -m unittest discover -v -s . -p "test_*.py"

deploy-docs:
  stage: deploy-docs
  image:
    name: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    pull_policy: [if-not-present, always]
  tags:
    - docker
  variables:
    SSH_USER: "runner"
    DEST_PATH: "/opt/stacks/caddy/site/docs/"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  <<: *env_setup
  script:
    # Build Docs
    - uv run sphinx-apidoc -f -o docs/source src/ms_camera_model/
    - uv run sphinx-build -b html docs/source docs/build/html
    
    # Set up SSH and Deploy
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p "$SSH_PORT" "$VPSHOST" >> ~/.ssh/known_hosts
    - rsync -avz --delete -e "ssh -p $SSH_PORT" docs/build/html/ "$SSH_USER@$VPSHOST:$DEST_PATH"
