# Pre-commit config

repos:
  - repo: https://github.com/google/yapf
    rev: v0.40.1
    hooks:
      - id: yapf
        name: yapf
        args: ['--style', '{based_on_style: google, column_limit: 120}']
