name: Deploy ms_camera_model docs to Caddy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up uv cache
        uses: actions/cache@v4
        with:
          path: /root/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install missing dependencies and rsync
        run: |
          apt update
          apt install -y libgdal-dev g++ libgl1 rsync
          echo "GDAL_VERSION=$(gdal-config --version)" >> $GITHUB_ENV

      - name: Sync with extras
        run: |
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          uv add "gdal==${{ env.GDAL_VERSION }}.*"
          uv sync --all-extras --dev

      - name: Build Docs
        run: |
          uv run sphinx-apidoc -f -o docs/source src/ms_camera_model/
          uv run sphinx-build -b html docs/source docs/build/html

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: runner
          VPS_HOST: ${{ vars.VPSHOST }}
          DEST_PATH: /opt/stacks/caddy/site/docs/
        run: |
          # Set up SSH agent
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Add host to known_hosts to avoid manual verification
          ssh-keyscan -p "$SSH_PORT" "$VPS_HOST" >> ~/.ssh/known_hosts
          
          # Run rsync
          rsync -avz --delete -e "ssh -p $SSH_PORT" docs/build/html/ "$SSH_USER@$VPS_HOST:$DEST_PATH"
